{% set version = "2.7.0" %}

package:
  name: pytest-factoryboy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest-factoryboy/pytest_factoryboy-{{ version }}.tar.gz
  sha256: 67fc54ec8669a3feb8ac60094dd57cd71eb0b20b2c319d2957873674c776a77b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry
    - python >=3.8
  run:
    - factory_boy >=2.10.0
    - inflection
    - packaging
    - pytest >=6.2.0
    - python >=3.8
    - typing_extensions

test:
  imports:
    - pytest_factoryboy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pytest-factoryboy.readthedocs.io
  summary: Factory Boy support for pytest.
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/pytest-dev/pytest-factoryboy

extra:
  recipe-maintainers:
    - cshaley
    - bollwyvl
