{% set version = "2.8.0" %}

package:
  name: pytest-factoryboy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest-factoryboy/pytest_factoryboy-{{ version }}.tar.gz
  sha256: bef3d1b087b20ff3b13b7c6ebcb8c13531b0eafa11fc47d7641600b2437dea7e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - pip
    - poetry-core
    - python {{ python_min }}
  run:
    - factory_boy >=2.10.0
    - inflection
    - packaging
    - pytest >=6.2.0
    - python >={{ python_min }}
    - typing_extensions

test:
  imports:
    - pytest_factoryboy
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pytest-factoryboy.readthedocs.io
  summary: Factory Boy support for pytest.
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/pytest-dev/pytest-factoryboy

extra:
  recipe-maintainers:
    - cshaley
    - bollwyvl
